[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "About"
pageRef = "about"
identifier = "kQFKIHZRH6"
weight = 1

[[main]]
pre = "github"
url = "https://github.com/grantwinney"
identifier = "IEzzirqXmL"
weight = 30

[[main]]
pre = "email"
url = "https://grantwinney.com/contact"
identifier = "jwjWIFj76z"
weight = 45

[[main]]
pre = "rss"
url = "https://grantwinney.com/index.xml"
identifier = "Npb6xugTVb"
weight = 50

[[footer]]
name = "Categories"
pageRef = "categories"
identifier = "kQFKIHZRN2"
weight = 10

[[footer]]
name = "Topics"
pageRef = "topics"
identifier = "kQLLIHZRN2"
weight = 20

[[footer]]
name = "Readme"
pageRef = "read-me"
identifier = "nWFKIHZ332"
weight = 30
