[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "About"
pageRef = "about"
identifier = "kQFKIHZRH6"
weight = 1

[[main]]
pre = "github"
url = "https://github.com/grantwinney"
identifier = "IEzzirqXmL"
weight = 30

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/grantwinney/"
identifier = "mHrXNYXipB"
weight = 40

[[main]]
pre = "email"
url = "contact"
identifier = "jwjWIFj76z"
weight = 45

[[main]]
pre = "rss"
url = "index.xml"
identifier = "Npb6xugTVb"
weight = 50

[[footer]]
none = "none"
