baseURL = 'https://example.org/'
description = 'A dev with questions... and answers too.'
languageCode = 'en-us'
title = 'Grant Winney'
theme = 'papermod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
  [[module.imports]]
    path = "papermod"
