baseURL = 'https://example.org/'
description = 'A dev with questions... and answers too.'
languageCode = 'en-us'
title = 'Grant Winney'
theme = ['papermod']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'

[outputs]
  home = ["HTML", "RSS", "JSON"]
