baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Grant Winney'
theme = 'papermod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'
